spring:
  application:
    name: picares
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picares
    username: root
    password: Mysql123

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 1h
#  s（秒）、m（分钟）、h（小时）、d（天）等。

logging:
  level:
    com.example.picares.mapper: debug
